apiVersion: apps/v1
kind: Deployment
metadata: 
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: users  
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: barnmutahi/user-api
          env:
            - name: AUTH_ADDRESS
              # value: "10.111.23.120" 
              value: "auth-service.default" 
        #       value: localhost
        # - name: auth
        #   image: barnmutahi/kube-demo-auth:latest